sudo: required

services:
  - docker

env:
  COMPOSE_VERSION: 1.24.1
#- COMPOSE_FILE=docker-compose.yml:docker-compose.override.travis.yml

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - docker --version
 - docker-compose --version
 - echo `which git`
 - echo $PWD
 - echo `uname -a`

script:
 - echo `date`
 - ./build-images.sh
 - ./start.sh 
 - docker ps
 - docker logs pg2mongo_pg1_1
 - docker exec -it pg2mongo_mongo_1 bash /p2m.sh 1 2
 - docker logs pg2mongo_mongo_1
 - docker exec -it pg2mongo_pg2_1 bash /data_gen.sh
 - echo `date`

#  - docker-compose build
#  - docker-compose run test

